# Generated by Django 5.2 on 2025-04-17 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_name', models.CharField(max_length=200, verbose_name='Название термина')),
                ('term_description', models.TextField(verbose_name='Описание термина')),
            ],
            options={
                'ordering': ['term_name'],
            },
        ),
    ]
