# Generated by Django 5.2 on 2025-04-17 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terms', '0002_feedback'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='term',
            options={},
        ),
        migrations.AddField(
            model_name='term',
            name='first_letter',
            field=models.CharField(default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='term',
            name='term_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='term',
            name='term_name',
            field=models.CharField(max_length=200),
        ),
    ]
