# Generated by Django 5.2 on 2025-04-18 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terms', '0004_alter_term_options_remove_term_first_letter_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Аты-жөні')),
                ('profession', models.CharField(max_length=100, verbose_name='Кәсібі')),
                ('text', models.TextField(verbose_name='Пікір')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Қосылған уақыты')),
            ],
            options={
                'verbose_name': 'Пікір',
                'verbose_name_plural': 'Пікірлер',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name': 'Кері байланыс', 'verbose_name_plural': 'Кері байланыс'},
        ),
        migrations.AlterField(
            model_name='feedback',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Жөнелту күні'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='message',
            field=models.TextField(verbose_name='Хабарлама'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Сіздің атыңыз'),
        ),
        migrations.AlterField(
            model_name='term',
            name='term_description',
            field=models.TextField(verbose_name='Терминнің сипаттамасы'),
        ),
        migrations.AlterField(
            model_name='term',
            name='term_name',
            field=models.CharField(max_length=200, verbose_name='Терминнің атауы'),
        ),
    ]
